### PR TITLE
Support for personal token

### PR DESCRIPTION
**Pull request by bitterbit**

### CODE REVIEW

**Comment by dorelljames** [comment]
Thanks for PR @bitterbit but I'll have to decline this as I don't want to support personal tokens yet until we can make sure the users of the plugin should make sure that their Git repo and Sanity dataset are set to plugin and storing such tokens is done via `sanity-studio-secrets`. Also, more on [this topic here](https://github.com/dorelljames/sanity-plugin-netlify-deploy-status-badge/issues/5#issuecomment-958739511).

**Comment by bitterbit** [comment]
Oh didn't know that, would be useful to mention this in the readme as I was thinking it said personal tokens were supported and didn't understand why it didn't work.

I'll read more about how to make it secure, would you be interested in it if I find a way to make it secure? 

Thanks man! Great plug-in :)

**Comment by dorelljames** [comment]
Yes, of course! I'll be happy to accept your contributions here on but for now I think the biggest priority is to use [sanity-studio-secrets](https://github.com/sanity-io/sanity-studio-secrets) for storing configuration options such as `OAuth Client ID`. As for personal access tokens, I'm not so sure. I'm contemplating just now if using disclaimers would be enough for us to get through. The last thing I really want is tokens being leaked everywhere. If only Netlify tokens can be generated just like of GitHub's, perhaps, it wouldn't be as destructive as it would be right now.

**Comment by bitterbit** [comment]
Not sure i fully understood you, why would sanity-studio-secrets not work for storing a personal access token? 
> we store secret information in a document in the dataset. This document will not be readable to externals even in a public dataset. With custom access controls you can also specify which users can read the configuration in your Studio.

Sounds really good to me

**Comment by gpoole** [comment]
@bitterbit storing personal access tokens via sanity-studio-secrets would be a security risk because under the hood it just stores the secrets in regular (hidden) documents, meaning the tokens would be accessible to anyone with a login - unless you restrict access via [custom roles](https://www.sanity.io/docs/roles), but that's an enterprise feature only. In my opinion it would not be a good idea to store a Netlify PAT there, since they give full admin access to your account and can't be configured in a granular way. Effectively any breach of any of your Sanity logins (or a malicious CMS user) could then lead to a compromise of your Netlify account via the token.

sanity-studio-secrets is probably best for storing keys that don't give significantly more access than the user would have via the GUI e.g. the Mux API token lets you manage video assets, but you can do that through the GUI too, so probably not a big deal if a CMS user can access it.

**Comment by bitterbit** [comment]
Actually it's the exact opposite. When using personal tokens the site owner has chosen explicitly to let all users to have access to this utility Netlify Account, they all have the UI button anyways.

When using OAuth tokens it is a security breach if one user can obtain tokens of another user.

**Pull request closed without merging**
